version: '3.7'
services:
  myapp:
    build: .
    container_name: project1
    restart: always
    ports:
      - 9000:8282
    volumes:
      - /opt/prj:/www
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo
    ports:
      - 27021:27017
    volumes:
      - /opt/mdb:/data/db
    
